apiVersion: apps/v1
kind: Deployment
metadata:
  name: msbae-deployment
  namespace: msbae
spec:
  selector:
    matchLabels:
      app: msbae
  replicas: 1
  template:
    metadata:
      labels:
        app: msbae
    spec:
      containers:
      - name: pods-msbae-deployment
        image: 056121157689.dkr.ecr.ap-south-1.amazonaws.com/msbae:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
         - name: tkiet-production-data
           mountPath: "/www/public/uploads/"
        env:
        - name: PROVISIONER_NAME
          value: efs-storage
        - name: NFS_SERVER
          value: 192.168.224.128
        - name: NFS_PATH
          value: /T01folder
      volumes:
      - name: tkiet-production-data
        nfs:
          server: 192.168.224.128
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: bynaricexamstudent-service
  namespace: allagents-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: bynaricexamstudent
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bynaricexamstudent-hpa
  namespace: allagents-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bynaricexamstudent-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
