---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msbae-deployment
  namespace: msbae
spec:
  selector:
    matchLabels:
      app: msbae
  replicas: 1
  template:
    metadata:
      labels:
        app: msbae
    spec:
      containers:
      - name: pods-msbae-deployment
        image: localhost:32000/msbae:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
         - name: doa-production-data
           mountPath: "/www/public/data"
        env:
        - name: PROVISIONER_NAME
          value: ksemin.in/nfs
        - name: NFS_SERVER
          value: 92.204.134.92
        - name: NFS_PATH
          value: /
      volumes:
      - name: doa-production-data
        nfs:
          server: 92.204.134.92
          path: /data/apps/doa
---
apiVersion: v1
kind: Service
metadata:
    name: msbae-service
    namespace: msbae
spec:
  selector:
    app: msbae
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: msbae-in-ingress
 namespace: msbae
 annotations:
   cert-manager.io/cluster-issuer: letsencrypt
spec:
 ingressClassName: public
 tls:
 - hosts:
   - msbae.in
   secretName: doa-in-ingress-tls
 rules:
 - host: msbae.in
   http:
     paths:
     - backend:
         service:
           name: msbae-service
           port:
             number: 80
       path: /
       pathType: Prefix
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: msbae-hpa
  namespace: msbae
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msbae-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
